### PR TITLE
Update the Readme

### PR DESCRIPTION
**Pull request by u625355**
docs: Updated the validation status in the support levels for the devices.

## Proposed changes

Update the readme with modifications in the support levels.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Documentation update (an update to enhance the user experience when reading through the docs)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have followed the guidelines in the [CONTRIBUTING](https://github.com/tektronix/tm_devices/blob/main/CONTRIBUTING.md) document
- [x] I have signed the CLA
- [x] I have checked to ensure there aren't other open [Pull Requests](https://github.com/tektronix/tm_devices/pulls) for the same update/change
- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Basic linting passes locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have added necessary documentation (if appropriate)
- [x] I have updated the Changelog with a brief description of my changes

### CODE REVIEW

**Review by nfelt14 — APPROVED** [review]
Please sign the CLA.

**Review by ldantek — APPROVED** [review]

**Comment by nfelt14** [comment]
@u625355, you need to rebase your branch with the main branch

**Review by qthompso — APPROVED** [review]

**Comment by nfelt14** [comment]
Please rebate from main and reopen the PR.

**Comment by nfelt14** [comment]
Please rebase from main and reopen the PR.

**Pull request closed without merging**
